#!/usr/bin/with-contenv bash

JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/ -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=config -Djava.util.logging.config.file=/config/logging.properties"

if [[ ! -z "$DOCKER_HOST_ADDRESS" ]]; then
    LOCAL_ADDRESS="$(hostname -I | cut -d " " -f1)"
    PUBLIC_ADDRESS="$(curl -4qs --connect-timeout 15 icanhazip.com)"
    PUBLIC_ADDRESS="${PUBLIC_ADDRESS:-${DOCKER_HOST_ADDRESS}}"
    REGION="$(whois ${PUBLIC_ADDRESS}|grep -im1 'Country'|awk '{print $2}')"
    JAVA_SYS_PROPS="$JAVA_SYS_PROPS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=$LOCAL_ADDRESS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=$PUBLIC_ADDRESS"
    JAVA_SYS_PROPS="$JAVA_SYS_PROPS -Dorg.jitsi.videobridge.octo.BIND_ADDRESS=$LOCAL_ADDRESS -Dorg.jitsi.videobridge.octo.PUBLIC_ADDRESS=$PUBLIC_ADDRESS -Dorg.jitsi.videobridge.REGION=$REGION"
fi

DAEMON=/usr/share/jitsi-videobridge/jvb.sh
DEFAULT_DAEMON_OPTS="none"

DAEMON_OPTS=${JVB_ENABLE_APIS:=$DEFAULT_DAEMON_OPTS}

exec s6-setuidgid jvb /bin/bash -c "JAVA_SYS_PROPS=\"$JAVA_SYS_PROPS\" exec $DAEMON --apis=${DAEMON_OPTS}"

