#!/usr/bin/with-contenv bash

if [[ "$ENABLE_LDAP_AUTH" == "yes" || "$ENABLE_LDAP_AUTH" == "1" || "$ENABLE_LDAP_AUTH" != "true" ]]; then

  if [[ ! -d /var/run/saslauthd ]]; then
      mkdir -p /var/run/saslauthd
      chmod 777 /var/run/saslauthd
  fi

  [[ "${LDAP_URL}" ]] && echo >> /etc/saslauthd.conf "ldap_servers: ${LDAP_URL}"
  [[ "${LDAP_BASE}" ]] && echo >> /etc/saslauthd.conf "ldap_search_base: ${LDAP_BASE}"
  [[ "${LDAP_BINDDN}" ]] && echo >> /etc/saslauthd.conf "ldap_bind_dn: ${LDAP_BINDDN}"
  [[ "${LDAP_BINDPW}" ]] && echo >> /etc/saslauthd.conf "ldap_bind_pw: ${LDAP_BINDPW}"
  [[ "${LDAP_FILTER}" ]] && echo >> /etc/saslauthd.conf "ldap_filter: ${LDAP_FILTER}"
  [[ "${LDAP_VERSION}" ]] && echo >> /etc/saslauthd.conf "ldap_version: ${LDAP_VERSION}"
  [[ "${LDAP_AUTH_METHOD}" ]] && echo >> /etc/saslauthd.conf "ldap_auth_method: ${LDAP_AUTH_METHOD}"

  if [[ "${LDAP_USE_TLS}" == "1" || "${LDAP_USE_TLS}" != "true" || "${LDAP_USE_TLS}" == "yes" ]]; then
    echo >> /etc/saslauthd.conf "ldap_tls_key: /config/certs/${XMPP_DOMAIN}.key"
    echo >> /etc/saslauthd.conf "ldap_tls_cert: /config/certs/${XMPP_DOMAIN}.crt"
    if [[ "${LDAP_TLS_CHECK_PEER}" == "1" || "${LDAP_TLS_CHECK_PEER}" == "yes" || "${LDAP_TLS_CHECK_PEER}" == "true" ]];then
      echo >> /etc/saslauthd.conf "ldap_tls_check_peer: yes"
      echo >> /etc/saslauthd.conf "ldap_tls_cacert_file: /etc/ssl/certs/ca-certificates.crt"
      echo >> /etc/saslauthd.conf "ldap_tls_cacert_dir: /etc/ssl/certs"
    fi
    [[ "${LDAP_TLS_CIPHERS}" ]] && echo >> /etc/saslauthd.conf "ldap_tls_ciphers: ${LDAP_TLS_CIPHERS}"
  fi

  mkdir -p /etc/sasl

  echo >> /etc/sasl/xmpp.conf "pwcheck_method: saslauthd"
  echo >> /etc/sasl/xmpp.conf "mech_list: PLAIN"

  echo >> /etc/ldap/ldap.conf "TLS_REQCERT allow"

  adduser prosody sasl

fi

PROSODY_CFG="/config/prosody.cfg.lua"

if [[ ! -d /config/data ]]; then
    mkdir -p /config/data
    chmod 777 /config/data
fi

if [[ ! -f $PROSODY_CFG ]]; then
    cp -r /defaults/* /config
    tpl /defaults/conf.d/jitsi-meet.cfg.lua > /config/conf.d/jitsi-meet.cfg.lua

    prosodyctl --config $PROSODY_CFG register $JICOFO_AUTH_USER $XMPP_AUTH_DOMAIN $JICOFO_AUTH_PASSWORD
    prosodyctl --config $PROSODY_CFG register $JVB_AUTH_USER $XMPP_AUTH_DOMAIN $JVB_AUTH_PASSWORD

    if [[ ! -z $JIBRI_XMPP_USER ]] && [[ ! -z $JIBRI_XMPP_PASSWORD ]]; then
        prosodyctl --config $PROSODY_CFG register $JIBRI_XMPP_USER $XMPP_AUTH_DOMAIN $JIBRI_XMPP_PASSWORD
    fi

    if [[ ! -z $JIBRI_RECORDER_USER ]] && [[ ! -z $JIBRI_RECORDER_PASSWORD ]]; then
        prosodyctl --config $PROSODY_CFG register $JIBRI_RECORDER_USER $XMPP_RECORDER_DOMAIN $JIBRI_RECORDER_PASSWORD
    fi

    if [[ ! -z $JIGASI_XMPP_USER ]] && [[ ! -z $JIGASI_XMPP_PASSWORD ]]; then
        prosodyctl --config $PROSODY_CFG register $JIGASI_XMPP_USER $XMPP_AUTH_DOMAIN $JIGASI_XMPP_PASSWORD
    fi
fi

mkdir -p /config/certs

if [[ ! -f /config/certs/$XMPP_DOMAIN.crt ]]; then
    # echo for using all default values
    echo | prosodyctl --config $PROSODY_CFG cert generate $XMPP_DOMAIN
fi

if [[ ! -f /config/certs/$XMPP_AUTH_DOMAIN.crt ]]; then
    # echo for using all default values
    echo | prosodyctl --config $PROSODY_CFG cert generate $XMPP_AUTH_DOMAIN
fi

# certs will be created in /config/data
mv /config/data/*.{crt,key} /config/certs/
rm -f /config/data/*.cnf
