#!/usr/bin/with-contenv bash

DAEMON="/usr/bin/Xorg -nolisten unix -nocursor -noreset +extension RANDR +extension RENDER -logfile /tmp/xorg1.log -config /etc/jitsi/jibri/xorg-display1.conf :1"
exec s6-setuidgid jibri /bin/bash -c "exec $DAEMON"

